#!/bin/bash
x1=$(cat /etc/shadow | grep $USER | cut -d: -f 3)
date "+Data da ultima alteração do user: %d/%m/%y" -d "1970-01-01 +$x1 days"

x2=$(expr $(date +%s) \/ 86400)
x3=$(expr $x2 - $x1)
echo "O numero de dias é: $x3"
